"""Create a deterministic zip with one complete task directory."""
import hashlib
import json
import os
import tempfile
import shutil
import stat
import zipfile
from pathlib import Path
from audit_submission import ROOT, TASK, audit
from runtime_contract import runtime_contract
from audit_revision import audit_revision

# Audit before writing anything, then refresh evidence generated by make audit.
audit()
revision_report = audit_revision()
(ROOT / "validation/revision-audit.json").write_text(json.dumps(revision_report, indent=2) + "\n")
for name in ("evidence-audit.json", "verifier-contract.json", "verifier-hardening.json", "revision-audit.json"):
    shutil.copy(ROOT / "validation" / name, TASK / "validation" / name)
out = ROOT / "submission"
out.mkdir(exist_ok=True)
archive = out / "collinear-siddharthshashankkumar.zip"
fd, staging_name = tempfile.mkstemp(prefix=".submission-", suffix=".zip", dir=out)
os.close(fd)
staging = Path(staging_name)
prefix = Path("collinear-siddharthshashankkumar/t20-exact-forecast")
with zipfile.ZipFile(staging, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as z:
    for path in sorted(TASK.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts or path.name == ".DS_Store":
            continue
        if path.is_symlink():
            raise ValueError(f"Unexpected symlink: {path}")
        info = zipfile.ZipInfo(str(prefix / path.relative_to(TASK)), date_time=(2026, 9, 26, 0, 0, 0))
        info.create_system = 3
        info.external_attr = (stat.S_IFREG | stat.S_IMODE(path.stat().st_mode)) << 16
        info.compress_type = zipfile.ZIP_DEFLATED
        z.writestr(info, path.read_bytes())
with zipfile.ZipFile(staging) as z:
    assert z.testzip() is None
    tasks = [n for n in z.namelist() if n.endswith("/task.toml")]
    assert tasks == [str(prefix / "task.toml")], tasks
    for script in ("solution/solve.sh", "tests/test.sh"):
        assert z.getinfo(str(prefix / script)).external_attr >> 16 & 0o111
    _, revision, expected_files = runtime_contract()
    for name, expected in expected_files.items():
        assert hashlib.sha256(z.read(str(prefix / name))).hexdigest() == expected, name
os.replace(staging, archive)
digest = hashlib.sha256(archive.read_bytes()).hexdigest()
archive.with_suffix(".zip.sha256").write_text(f"{digest}  {archive.name}\n")
print(f"Submission: {archive.relative_to(ROOT)} ({archive.stat().st_size:,} bytes)")
print(f"One task, version {revision['version']}; {len(expected_files)} runtime hashes and executable modes verified. SHA-256: {digest}")
